const trades = require('./trades')
const companyProfile = require('./companyProfile')
const fundOwnership = require('./fundOwnership')
const peers = require('./peers')
const priceTargets = require('./priceTargets')
const recommendationTrends = require('./recommendationTrends')
const quote = require('./quote')
const stockSymbols = require('./stockSymbols')
const newsSentiment = require('./newsSentiment')

trades.start()
quote.start()
companyProfile.updateCompanyProfile.start()
fundOwnership.fundOwnership.start()
peers.updatePeers.start()
priceTargets.priceTarget.start()
recommendationTrends.updateRecommendationTrends.start()
stockSymbols.stockSymbols.start()
newsSentiment.updateNewsSentiment.start()
